# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install dependencies
WORKDIR /app
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN npm ci --ignore-scripts && npm run build

CMD ["node", "dist/index.js"]
